export const REGISTRATION_ROUTE = '/registration'
export const AUTH_ROUTE = '/auth'
export const PAYMENT_ROUTE = '/payment'
export const MAIN_ROUTE = '/'
export const ACTIVITYTRACKER_ROUTE = '/activityTracker'
export const WEEKTRACKER_ROUTE = '/weekTracker'